// src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Input.vue
<template>
  <input :type="type" :placeholder="placeholder" :value="modelValue" @input="updateValue" />
</template>

<script>
export default {
  name: "Input",
  props: ["type", "placeholder", "modelValue"],
  methods: {
    updateValue(event) {
      this.$emit('update:modelValue', event.target.value);
    },
  },
};
</script>

// src/Frameworks/CSSFrameworks/React/bootstrap/atoms/Input.js
import { Form } from "react-bootstrap";

function Input({ placeholder, type, onChange, id, value, name }) {
    return (
        <Form.Control
            placeholder={placeholder}
            type={type}
            id={id}
            onChange={onChange}
            value={value}
            name={name}
        />
    );
}

export default Input;
