// src/templates/vue/src/components/organisms/Modal.vue
<template>
  <b-modal :id="id">
    <template #modal-header>
      <h5 class="m-0">{{ title }}</h5>
      <button class="btn-close fs-7" @click="$bvModal.hide(id)"></button>
    </template>
    <slot name="body" />
    <template #modal-footer>
      <slot name="footer" />
    </template>
  </b-modal>
</template>
  
<script>
export default {
  name: "Modal",
  props: ["id", "title"],
};
</script>

// src/templates/react/src/components/bootstrap/organisms/Modal.js
import { Modal } from 'react-bootstrap'

export default function ViceModal({
	children,
	show,
	handleClose,
	footer,
	title,
	size = 'sm-down',
}) {
	return (
		<Modal show={show} onHide={handleClose} size={size}>
			<Modal.Header className='border-0'>
				<Modal.Title className='f-32 font-semi-bold'>{title}</Modal.Title>
				<button className='btn-close' onClick={handleClose}></button>
			</Modal.Header>
			<Modal.Body className='py-0 mb-0'>{children}</Modal.Body>
			<Modal.Footer className='justify-content-between border-0'>
				{footer}
			</Modal.Footer>
		</Modal>
	)
}
