// src/themeProviderTemplates/react-themes/theme.js
import BootstrapSwitchButton from 'bootstrap-switch-button-react'
import React, { useState, useEffect } from 'react'
import { THEMES } from './theme.constants'

const THEME = 'theme'

export const ThemeToggler = () => {
  const [isDarkTheme, setIsDarkTheme] = useState(false)

  useEffect(() => {
    const isDarkThemeSelected = localStorage.getItem(THEME) === THEMES.DARK
    setIsDarkTheme(isDarkThemeSelected)

    if (isDarkThemeSelected)
      document.documentElement.classList.add(THEMES.DARK)
    else document.documentElement.classList.remove(THEMES.DARK)
  }, [])

  const handleThemeChange = (isChecked) => {
    if (isChecked) document.documentElement.classList.add(THEMES.DARK)
    else document.documentElement.classList.remove(THEMES.DARK)

    const selectedTheme = isChecked ? THEMES.DARK : THEMES.LIGHT
    localStorage.setItem(THEME, selectedTheme)
    setIsDarkTheme(isChecked)
  }

  return (
    <BootstrapSwitchButton
      className='DarkToggle'
      checked={isDarkTheme}
      width={50}
      offlabel='🌙'
      onlabel='🔆'
      onstyle='secondary'
      onChange={(event) => handleThemeChange(event)}
      aria-label='Dark mode'
    />
  )
}

// src/Providers/ThemeProviders/vue-themes/theme.vue
<template>
  <% if(isBootstrap) {%>
    <div class="fs-4" @click="ThemeToggler">
      <i :class="mode === DARK ? 'fa-solid fa-sun' : 'fa-sharp fa-solid fa-moon'"></i>
    </div>
  <%}%>
  <% if(isTailWind) {%>
    <div class="text-xl" @click="ThemeToggler">
    <button
      :class="mode === DARK ? ' text-white fa-solid fa-sun' : 'fa-sharp fa-solid fa-moon'" />
  </div>
  <%}%>
</template>

<script>
import { THEMES } from './theme.constants.js'

const { DARK, LIGHT }  = THEMES
const htmlClass = document.documentElement.classList;

export default {
  name: "Theme",
  data () {
    return {
      mode: localStorage.mode || LIGHT,
      DARK
    };
  },
  mounted () {
    if (this.mode && this.mode === DARK) htmlClass.add(DARK);
  },
  methods: {
    ThemeToggler() {
      this.mode === DARK ? htmlClass.remove(DARK) : htmlClass.add(DARK);
      this.mode = this.mode === DARK ? LIGHT : DARK
      localStorage.mode = this.mode
    },
  }
};
</script>
