// src/vuexTemplates/userModal/AddUser.vue
<template>
  <div>
    <Button type="button" color="primary" name="Add User" data-bs-toggle="modal" data-bs-target="#bv-modal-addUser" @onClick="showAddUserModal"/>

    <Modal id="bv-modal-addUser" title="Add User">
      <template #body>
        <form>
          <div class="mb-3">
            <Label inputId="name-input" class="form-label" name="Name"></Label>
            <input
              type="text"
              class="form-control"
              id="name-input"
              placeholder="Name"
              v-model="name"
            />
          </div>
          <div class="mb-3">
            <Label
              inputId="username-input"
              class="form-label"
              name="Username"
            ></Label>
            <input
              type="text"
              class="form-control"
              id="username-input"
              placeholder="Username"
              v-model="username"
            />
          </div>
          <div class="mb-3">
            <Label
              inputId="email-input"
              class="form-label"
              name="Email"
            ></Label>
            <input
              type="text"
              class="form-control"
              id="email-input"
              placeholder="example@email.com"
              v-model="email"
            />
          </div>
        </form>
      </template>
      <template #footer>
        <Button type="submit" color="primary" data-bs-dismiss="modal" @submit="onSubmit" name="Add User"></Button>
        <Button type="button" color="outline-secondary" data-bs-dismiss="modal" name="Close" ></Button>
      </template>
    </Modal>
  </div>
</template>

<script>
import Button from "../components/atoms/Button";
import Label from "../components/atoms/Label";
import Modal from "../components/organisms/Modal";

const emptyString = "";

export default {
  name: "AddUser",
  components: {
    Label,
    Button,
    Modal
  },
  data() {
    return {
      name: null,
      username: null,
      email: null,
    };
  },
  methods: {
    onSubmit() {
      const data = {
        name: this.name,
        username: this.username,
        email: this.email,
      };
      this.$store.dispatch("addUser", data);
    },
    showAddUserModal() {
      this.name = emptyString;
      this.username = emptyString;
      this.email = emptyString;
    },
  },
};
</script>

// src/templates/angular/src/app/user/add-user/add-user.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/module/user';
import { userState } from '../store/reducer/user.reducer';
import { addUser } from '../store/action/user.actions';
import { Store } from '@ngrx/store';
import { FormGroup,FormBuilder,FormControl } from '@angular/forms';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-add-user',
  templateUrl: './add-user.component.html',
  styleUrls: ['./add-user.component.css']
})
export class AddUserComponent implements OnInit {
  userForm: FormGroup ;
  constructor(private store: Store<userState>,private modalService: NgbModal) {
      }
      open(addusermodal:any) {
        this.modalService.open(addusermodal, {ariaLabelledBy: 'modal-basic-title'})   
      }    
      adduser(): void {
        const user: User = {
          id:this.userForm.value.id,
          name: this.userForm.value.name,
          username: this.userForm.value.username,
          email: this.userForm.value.email,
        };
        this.store.dispatch(addUser({user}));
        this.userForm.reset();
      }
  ngOnInit(): void {
    this.userForm = new FormGroup({
      id:new FormControl(),
     name: new FormControl(),
     username: new FormControl(),
    email: new FormControl()
    })
  }
}

    <ng-template #addusermodal let-modal>
      <div class="modal-header">
        <h4 class="modal-title" id="modal-basic-title">Add User</h4>
        <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form [formGroup]="userForm" >
          <div class="form-group">
                <div class="mb-3">
                    <label>Name</label>
                    <input type="text" class="form-control" formControlName="name" placeholder="Enter Name" />
                  </div>
                  <div class="mb-3">
                    <label>UserName</label>
                    <input type="username" class="form-control" formControlName="username" placeholder="Enter UserName"/>
                    </div>  
                  <div class="mb-3">
                    <label>Email</label>
                    <input type="email" class="form-control" formControlName="email" placeholder="Enter Email" />
                    </div>
            </div>
            </form> 
      </div>
      <div class="modal-footer">
        <button type="button"  class="btn btn-primary" (click)="modal.close(adduser())">ADD</button>
      </div>
    </ng-template>
    <div style="text-align: center;">
    <button class="btn btn-primary" (click)="open(addusermodal)">Add User</button>
    </div>
