// src/Frameworks/CSSFrameworks/React/tailwind/atoms/Button.js
function Button({ variant, name, color, onClick, align }) {
    return (
        <button
            type='button'
            className={`${color} ${align} font-medium ${variant} text-sm px-5 py-2.5 mr-2 mb-2 `}
            onClick={() => onClick()}
        >
            {name}
        </button>
    );
}

export default Button;

// src/templates/vue/src/components/atoms/Button.vue
<template>
  <div>
    <b-button :id="id" :class="className" :variant="color" v-on:click="$emit('submit')" @click="$emit('onClick')">{{ name }}</b-button>
  </div>
</template>

<script>
export default {
  name: "Button",
  props: ["id", "className", "name", "color", "onClick", "submit"],
};
</script>
