// src/Frameworks/WebFrameworks/react/src/components/tailwind/organisms/Modal.js
export default function TavaJSModal({ children, handleClose, title, footer }) {
	return (
		<div className='justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none  '>
			<div className='relative my-6 mx-auto w-96'>
				<div className='bg-white dark:text-white dark:bg-[#44403c] rounded-lg shadow-lg relative flex flex-col w-full outline-none focus:outline-none'>
					<div className='flex items-start justify-between p-5  rounded-t '>
						<h3 className='text-3xl font-semibold '>{title}</h3>
						<button
							className='p-1 ml-auto bg-transparent border-0 text-black float-right text-3xl leading-none font-semibold outline-none focus:outline-none'
							onClick={() => handleClose(false)}
						>
							<span className=' dark:text-white  h-6 w-6 text-2xl block outline-none focus:outline-none'>
								x
							</span>
						</button>
					</div>

					<div className='relative p-6 flex-auto '>
						<p className='my-4 text-lg leading-relaxed '>{children}</p>
					</div>

					<div className='flex items-center justify-end p-6 rounded-b '>
						{footer}
					</div>
				</div>
			</div>
		</div>
	)
}

// src/templates/vue/src/tailwind/components/organisms/Modal.vue
<template>
  <transition
    enter-active-class="transition ease-out duration-200 transform"
    enter-from-class="opacity-0"
    enter-to-class="opacity-100"
    leave-active-class="transition ease-in duration-200 transform"
    leave-from-class="opacity-100"
    leave-to-class="opacity-0"
  >
    <div
      ref="modal-backdrop"
      v-show="show"
      class="fixed z-10 inset-0 overflow-y-auto bg-black bg-opacity-50"
    >
      <div
        class="flex items-start justify-center min-h-screen pt-24 text-center"
      >
        <transition
          enter-active-class="transition ease-out duration-300 transform "
          enter-from-class="opacity-0 translate-y-0 scale-95"
          enter-to-class="opacity-100 translate-y-10 scale-100"
          leave-active-class="ease-in duration-200"
          leave-from-class="opacity-100 translate-y-10 scale-100"
          leave-to-class="opacity-0 translate-y-10 translate-y-10 scale-95"
        >
          <div
            id="modal"
            v-show="show"
            class="bg-white fixed shadow-lg overflow-hidden rounded-2xl flex flex-col justify-between w-full max-w-lg dark:bg-vueBlack"
          >
            <!-- Modal Header -->
            <header id="modal-header" class="flex border-white">
              <slot name="header"></slot>
            </header>

            <!-- Modal Body  -->
            <section id="modal-body" class="px-4 py-6">
              <slot name="body"></slot>
            </section>

            <!-- Modal Footer  -->
            <footer id="modal-footer" class="ml-auto border-white">
              <slot name="footer"></slot>
            </footer></div
        ></transition>
      </div></div
  ></transition>
</template>

<script>
export default {
  name: "Modal",
  methods: {},
  props: {
    show: {
      type: Boolean,
      default: false,
    },
  }
};
</script>
