// src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Button.vue
<template>
  <b-button :id="id" :size="size" :variant="color" :disabled="isDisabled" v-on:click="$emit('submit')" @click="$emit('onClick')">{{ name }}</b-button>
</template>

<script>
export default {
  name: "Button",
  props: ["id", "size", "name", "color", "onClick", "submit", "isDisabled"],
};
</script>

// src/Frameworks/CSSFrameworks/React/tailwind/atoms/Button.js
function Button({ variant, name, color, onClick, align }) {
    return (
        <button
            type='button'
            className={`${color} ${align} font-medium ${variant} text-sm px-5 py-2.5 mr-2 mb-2 `}
            onClick={() => onClick()}
        >
            {name}
        </button>
    );
}

export default Button;
