// src/templates/react/src/components/tailwind/organisms/NavBar.js
import Routes from '../../Routes'
import { BrowserRouter as Router } from 'react-router-dom'
<% if(isAuth0) {%>import { useAuth0 } from '../../react-spa'<%}%>
<% if(isOkta) {%>import AppWithRouterAccess from '../../oktaFiles/AppWithRouterAccess'<%}%>
<% if(isThemeProvider) { %>import { ThemeToggler } from '../../theme'<% } %>
const NavBar = ({ brand, links }) => {
	<% if(isAuth0) {%>const { logout } = useAuth0()<%}%>
	return (
		<Router>
			<nav className=' border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-[#1d1717]'>
				<div className='flex justify-start container items-center mx-auto'>
					<span className='self-center text-xl font-bold whitespace-nowrap dark:text-white'>
						{brand}
					</span>
					<button
						data-collapse-toggle='navbar-default'
						type='button'
						className='inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 '
						aria-controls='navbar-default'
						aria-expanded='false'>
						<span className='sr-only'>Open main menu</span>
						<svg
							className='w-6 h-6'
							aria-hidden='true'
							fill='currentColor'
							viewBox='0 0 20 20'
							xmlns='http://www.w3.org/2000/svg'>
							<path
								fillRule='evenodd'
								d='M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z'
								clipRule='evenodd'
							></path>
						</svg>
					</button>

					<div
						className='hidden w-full md:block md:w-auto dark:text-white'
						id='navbar-default'>
						<ul className='flex justify-start p-4 mt-4 rounded-lg border md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 dark:text-white dark:bg-[#1d1717]'>
							{links.map((each) => (
								<li key={each.key}>
									<a
										href={each.href}
										className='block py-2 pr-4 pl-3 rounded md:bg-transparent md:p-0 dark:text-white'
										aria-current='page'>
										{each.label}
									</a>
								</li>
							))}
						</ul>
					</div>
					<div className='grow'>
						<div className='float-right'>
						<% if(isAuth0) {%>
						<ul>
							<li
								onClick={() => logout({ returnTo: window.location.origin })}
							>
								Logout
							</li>
						</ul>
						<%}%>
						</div>
					</div>
					<% if(isOkta) { %><AppWithRouterAccess /> <% } %>
					<% if(isThemeProvider) { %><ThemeToggler/><% } %>
				</div>
			</nav>
			<Routes />
		</Router>
	)
}
export default NavBar

// src/templates/vue/src/components/tailwind/organisms/Navbar.vue
<template>
<nav class="bg-white dark:bg-black border-gray-200 px-2">
  <div class="container flex flex-wrap items-center lg:justify-start mt-3 w-full">
    <div>
      <a href="#" class="flex">
        <span class="self-center text-xl dark:text-white ml-2  whitespace-nowrap">Made In India</span>
      </a>
    </div>
    <div class="flex ml-auto sm:ml-3">
      <button  type="button" class="md:hidden text-gray-400 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300 
        rounded-lg inline-flex items-center justify-center" 
        v-on:click="toggleNavbar()"
      >
        <span class="sr-only">Open  menu</span>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
    <div class="md:block w-full md:w-auto" v-bind:class="{'hidden': !showMenu }" >
      <ul class="flex-col md:flex-row flex md:space-x-1 mt-1">
        <li>
          <a href="/" class="text-gray-500 hover:text-black block pl-3 text-base pr-4 py-2">Home</a>
        </li>
        <li>
          <a href="/users" class="text-gray-500 hover:text-black block pl-3 text-base pr-4 py-2 space-x-8" >Users</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>

<script>
export default{
 name:"Navbar",
 data() {
    return {
      showMenu: false,
      isDark:false
    }
  },
  methods: {
    toggleNavbar: function() {
      this.showMenu = !this.showMenu;
    }
  }
}
</script>
