// src/templates/react/src/widgets/NavBar/NavBar.js
import React from 'react'
import Routes from "../../Routes";
import { BrowserRouter as Router,Link } from "react-router-dom";
import 'bootstrap/dist/css/bootstrap.min.css';
import {Container,Navbar,Nav} from 'react-bootstrap'
<% if(isAuth0) {%>import { useAuth0 } from "../../react-spa";<%}%>

export default function NavBar() {
  <% if(isAuth0) {%>const { logout } = useAuth0();<%}%>
  return (
    <>
      <Router>
        <Navbar bg="light" expand="lg">
          <Container>
            <Navbar.Brand href="#home">Made in India</Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
              <Nav className="me-auto">
                <Link to="/home"><Nav.Link href="/home">Home</Nav.Link></Link>
                <Link to="/users"><Nav.Link href="/users">Users</Nav.Link></Link>
              </Nav>
              <% if(isAuth0) {%><Nav>
                <Nav.Link
                  onClick={() => logout({ returnTo: window.location.origin })}
                >
                  Logout
                </Nav.Link>
              </Nav><%}%>
              
            </Navbar.Collapse>
          </Container>
        </Navbar>
        <Routes />
      </Router>
    </>
  );
}

// src/templates/vue/src/components/organisms/Navbar.vue
<template>
  <b-navbar toggleable="lg">
    <b-navbar-brand class="mx-4" href="#">Made in India</b-navbar-brand>

    <b-navbar-toggle class="mx-4" target="nav-collapse"></b-navbar-toggle>

    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav class="ml-auto">
        <b-nav-item to="/">Home</b-nav-item>
        <b-nav-item to="/users">Users</b-nav-item>
      </b-navbar-nav>
    </b-collapse>

    <% if(isDark) { %> 
    <b-navbar-nav class="mx-2">
      <ThemeVue/>
    </b-navbar-nav>
    <% } %> 
    <% if(isAuth0) { %> 
    <b-navbar-nav class="mx-2">
      <LogoutButton/>
    </b-navbar-nav>
    <% } %> 
  </b-navbar>
</template>

<script>
<% if(isDark) { %> 
import ThemeVue from '../../theme.vue';
<% } %> 
<% if(isAuth0) { %> 
import LogoutButton from '../atoms/LogoutButton.vue'
<% } %> 
export default {
  name: "Navbar",
  components : {
  <% if(isDark) { %> 
    ThemeVue,
  <% } %>   
  <% if(isAuth0) { %> 
    LogoutButton,
  <% } %>   
  },
};
</script>
